// Add real apps here in display order. Until then, the page shows labeled samples.
// Registered apps use the same glass placards; more records extend the horizontal shelf.
// Icon paths are relative to this page, e.g. "./assets/apps/your-app.png".
// See README.md for the full app record format.
export const apps = [];

export const copy = {
  en: {
    "page.title": "VANILLA ISN’T BAD. — Good as it is.",
    "page.description": "Apps that feel good from the start, with room to make them your own. VANILLA ISN’T BAD.",
    "nav.skip": "Skip to the apps",
    "nav.apps": "Apps",
    "nav.about": "Our take",
    "hero.description": "",
    "hero.cta": "Explore the apps",
    "kiosk.caption": "VANILLA ISN’T BAD. — a little ice-cream shop in the park, with cones, cups and three vanilla trays beneath the serving window.",
    "kiosk.link": "Explore the apps",
    "gallery.title": "APPS",
    "gallery.empty": "In the making.",
    "gallery.preview": "Sample apps for this preview.",
    "shelf.label": "App shelf",
    "shelf.help": "Swipe horizontally, or use the left and right arrow keys to browse the shelf. Home and End move to either end.",
    "shelf.previous": "Previous apps",
    "shelf.next": "Next apps",
    "preview.focus": "Focus timer",
    "preview.notes": "Keep a note",
    "preview.trip": "Plan a trip",
    "preview.tasks": "Sort tasks",
    "preview.budget": "Track costs",
    "preview.journal": "Save a day",
    "about.title": "Start with how it feels.",
    "about.description": "Like vanilla, good on its own.\nWe make apps that feel right from the start, with room to make them yours.",
    "footer.top": "Back to the sky",
    "dialog.close": "Close app details",
    "dialog.open": "Open app",
    "dialog.soon": "More details soon.",
    "app.details": "View details",
    "motion.label": "Motion",
    "motion.on": "On",
    "motion.off": "Off"
  },
  ja: {
    "page.title": "VANILLA ISN’T BAD. — Good as it is.",
    "page.description": "足さなくてもいい。だけど、足してもいい。VANILLA ISN’T BAD. は、基本の使い心地を大切にするアプリをつくります。",
    "nav.skip": "アプリ一覧へ",
    "nav.apps": "アプリ",
    "nav.about": "私たちの考え",
    "hero.description": "足さなくてもいい。\nだけど、足してもいい。",
    "hero.cta": "アプリを見る",
    "kiosk.caption": "公園の小さなアイス屋、VANILLA ISN’T BAD.。丸い屋根、コーンとカップのある注文窓、その下に三つのバニラアイスのケースが並びます。",
    "kiosk.link": "アプリ一覧を見る",
    "gallery.title": "APPS",
    "gallery.empty": "ただいま準備中。",
    "gallery.preview": "表示確認用のサンプルです。",
    "shelf.label": "アプリの棚",
    "shelf.help": "横にスワイプ、または左右の矢印キーで棚を移動できます。Homeキーで最初、Endキーで最後へ移動します。",
    "shelf.previous": "前のアプリへ",
    "shelf.next": "次のアプリへ",
    "preview.focus": "集中を計る",
    "preview.notes": "メモを残す",
    "preview.trip": "旅を計画",
    "preview.tasks": "タスクを整理",
    "preview.budget": "支出を記録",
    "preview.journal": "日々を記録",
    "about.title": "まず、使い心地を\n味わってみてください。",
    "about.description": "何も足さなくてもおいしいバニラアイスのように。\n\nトッピングのように。\n必要な分だけあなたに合わせます。",
    "footer.top": "空へ戻る",
    "dialog.close": "アプリの詳細を閉じる",
    "dialog.open": "アプリを開く",
    "dialog.soon": "詳細は準備中です。",
    "app.details": "詳しく見る",
    "motion.label": "動き",
    "motion.on": "あり",
    "motion.off": "なし"
  }
};
