// Add real apps here. Empty shelves are intentional until assets are supplied.
// Icon paths are relative to this page, e.g. "./assets/apps/your-app.png".
// See README.md for the full app record format.
export const apps = [];

export const copy = {
  en: {
    "page.title": "VANILLA ISN'T BAD. — Small apps, thoughtfully made.",
    "page.description": "Simple is enough. A small collection of thoughtful apps from VANILLA ISN'T BAD.",
    "nav.skip": "Skip to the apps",
    "nav.apps": "Apps",
    "nav.about": "Our take",
    "hero.eyebrow": "SMALL APPS. THOUGHTFULLY MADE.",
    "hero.title": "Simple is enough.",
    "hero.description": "A little less fuss. A little more room for the good things.",
    "hero.cta": "Find your little good thing",
    "kiosk.caption": "Our little storefront, with a vanilla-striped awning and room for apps.",
    "kiosk.link": "Explore the apps",
    "gallery.eyebrow": "ON THE SHELF",
    "gallery.title": "A few good things.",
    "gallery.description": "Small apps, each with a little purpose.",
    "gallery.empty": "A little room for what's next.",
    "gallery.emptyNote": "Thoughtful little things are in the making.",
    "about.eyebrow": "OUR TAKE",
    "about.title": "Good doesn't have to be loud.",
    "about.description": "We like things that do their job, feel good to use, and leave a little room to breathe. That's the kind of app we want to make.",
    "about.signature": "Vanilla isn't bad, after all.",
    "footer.top": "Back to the sky",
    "footer.note": "A little less. A little better.",
    "dialog.close": "Close app details",
    "dialog.open": "Open app",
    "dialog.soon": "More details soon.",
    "app.details": "View details",
    "motion.label": "Motion",
    "motion.on": "On",
    "motion.off": "Off"
  },
  ja: {
    "page.title": "VANILLA ISN'T BAD. — 気の利いた、小さなアプリ。",
    "page.description": "シンプルでいい。VANILLA ISN'T BAD. の小さなアプリたち。",
    "nav.skip": "アプリ一覧へ",
    "nav.apps": "アプリ",
    "nav.about": "私たちの考え",
    "hero.eyebrow": "SMALL APPS. THOUGHTFULLY MADE.",
    "hero.title": "シンプルでいい。",
    "hero.description": "手間を少し減らして、好きなことの余白を。",
    "hero.cta": "小さな「いい」を見つける",
    "kiosk.caption": "バニラ色の日よけと、アプリを並べる棚のある小さなお店。",
    "kiosk.link": "アプリ一覧を見る",
    "gallery.eyebrow": "ON THE SHELF",
    "gallery.title": "小さな「いい」を、いくつか。",
    "gallery.description": "それぞれに、小さな役割のあるアプリ。",
    "gallery.empty": "次の楽しみのための、少しの余白。",
    "gallery.emptyNote": "気の利いた小さなものを、準備しています。",
    "about.eyebrow": "OUR TAKE",
    "about.title": "良さは、静かでも伝わる。",
    "about.description": "ちゃんと役に立って、使っていて気持ちがいい。暮らしに少し、余白ができる。そんなアプリをつくりたいと思っています。",
    "about.signature": "ふつうも、悪くない。",
    "footer.top": "空へ戻る",
    "footer.note": "少し減らして、少しよくする。",
    "dialog.close": "アプリの詳細を閉じる",
    "dialog.open": "アプリを開く",
    "dialog.soon": "詳細は準備中です。",
    "app.details": "詳しく見る",
    "motion.label": "動き",
    "motion.on": "あり",
    "motion.off": "なし"
  }
};
